mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zzw.studentmanager.pojo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///student
    username: root
    password: root